# Generated by Django 3.0.2 on 2020-02-03 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200202_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 9, 30, 44, 412117, tzinfo=utc)),
        ),
    ]
