# Generated by Django 3.0.2 on 2020-02-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(max_length=1000, null=True, upload_to=''),
        ),
    ]
