# Generated by Django 3.0.2 on 2020-02-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanel', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='law',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
