# Generated by Django 3.0.2 on 2020-02-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanel', '0003_chanel_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='title',
            field=models.CharField(default='test', max_length=150),
        ),
    ]
