# Generated by Django 3.0.2 on 2020-02-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filemodel',
            table='file',
        ),
    ]
