# Generated by Django 3.0.2 on 2020-02-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
